//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFWebAPIAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class PODETAIL
    {
        [DataMember]
        public string PONO { get; set; }
        [DataMember]
        public string ITCODE { get; set; }
        [DataMember]
        public Nullable<int> QTY { get; set; }

        public virtual ITEM ITEM { get; set; }
        public virtual POMASTER POMASTER { get; set; }
    }
}
